/*El prefijo TC_ corresponde a Tienda Comic */
CREATE TABLE TC_PERSONA
( SPID number(10) NOT NULL,
  SCNOMBRE varchar2(50) NOT NULL,
  SCNUMIDENTIFICACION number(10) NOT NULL,
  CONSTRAINT TC_PERSONA_PK PRIMARY KEY (SPID)
);



COMMENT ON COLUMN "TC_PERSONA"."SPID" IS 'Identificador unico de la persona';
COMMENT ON COLUMN "TC_PERSONA"."SCNOMBRE" IS 'Nombre completo de la persona';
COMMENT ON COLUMN "TC_PERSONA"."SCNUMIDENTIFICACION" IS 'Numero de cedula de la persona';

CREATE SEQUENCE "DB_SEMILLERO"."SEQ_PERSONA" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;

insert into TC_PERSONA (SPID,SCNOMBRE, SCNUMIDENTIFICACION)
values (DB_SEMILLERO.SEQ_PERSONA.nextval,'Luisa Micolta',210020);
insert into TC_PERSONA (SPID,SCNOMBRE, SCNUMIDENTIFICACION)

values (DB_SEMILLERO.SEQ_PERSONA.nextval,'Carlos Montoya',234140);

insert into TC_PERSONA (SPID,SCNOMBRE, SCNUMIDENTIFICACION)
values (DB_SEMILLERO.SEQ_PERSONA.nextval,'Camilo Cardenas',15263020);

insert into TC_PERSONA (SPID,SCNOMBRE, SCNUMIDENTIFICACION)
values (DB_SEMILLERO.SEQ_PERSONA.nextval,'Alejandra Sanabria',57320020);

CREATE TABLE TC_USUARIO
( SUID number(10) NOT NULL,
  SUNOMBRE varchar2(50) NOT NULL,
  SUFECHA_CREACION  DATE,
  SUESTADO VARCHAR2(50 BYTE),
  SUIDPERSONA number(10) NOT NULL,
  CONSTRAINT TC_USUARIO_PK PRIMARY KEY (SUID),
  CONSTRAINT TC_USUARIO_1 CHECK (SUESTADO IN ('ACTIVO', 'INACTIVO')) ENABLE,
  CONSTRAINT TC_FK_USUARIO_PERSONA
    FOREIGN KEY (SUIDPERSONA)
    REFERENCES TC_PERSONA(SPID)
);


COMMENT ON COLUMN "TC_USUARIO"."SUID" IS 'Identificador unico del usuario';
COMMENT ON COLUMN "TC_USUARIO"."SUNOMBRE" IS 'Nombre de usuario';
COMMENT ON COLUMN "TC_USUARIO"."SUFECHA_CREACION" IS 'Fecha en la que se crea el usuario';
COMMENT ON COLUMN "TC_USUARIO"."SUESTADO" IS 'Define si el usuario esta activo o no';
COMMENT ON COLUMN "TC_USUARIO"."SUIDPERSONA" IS 'Referencia con la persona due�a del usuario';

CREATE SEQUENCE "DB_SEMILLERO"."SEQ_USUARIO" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;

CREATE TABLE TC_PROVEEDOR
( SPID number(10) NOT NULL,
  SPDIRECCION varchar2(50) NOT NULL,
  SPFECHA_CREACION  DATE,
  SPESTADO VARCHAR2(50 BYTE),
  SPIDPERSONA number(10) NOT NULL,
  SPMONTO_CREDITO number(20) NOT NULL,
  CONSTRAINT TC_PROVEEDOR_PK PRIMARY KEY (SPID),
  CONSTRAINT TC_PROVEEDOR_1 CHECK (SPESTADO IN ('ACTIVO', 'INACTIVO')) ENABLE,
  CONSTRAINT TC_FK_PROVEEDOR_PERSONA
    FOREIGN KEY (SPIDPERSONA)
    REFERENCES TC_PERSONA(SPID)
);


CREATE SEQUENCE "DB_SEMILLERO"."SEQ_PROVEEDOR" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;



insert into TC_PROVEEDOR (SPID,SPDIRECCION,SPFECHA_CREACION, SPESTADO,SPIDPERSONA,SPMONTO_CREDITO)
values (DB_SEMILLERO.SEQ_PROVEEDOR.nextval,'Cra 19 # 7 BIS 13',sysdate,'ACTIVO',2,56773243);

CREATE TABLE TC_FACTURA
( SFID NUMBER(10) NOT NULL,
  SFCLIENTE NUMBER(10),
  SFPROVEEDOR NUMBER(10),
  SFIVA NUMBER(10) NOT NULL,
  SFTOTAL NUMBER(10) NOT NULL,
  SFTIPO VARCHAR2(50 BYTE),
  SFESTADO VARCHAR2(50 BYTE),
  CONSTRAINT TC_FACTURA_1 CHECK (SFTIPO IN ('PEDIDO', 'VENTA')) ENABLE, 
  CONSTRAINT TC_FACTURA_2 CHECK (SFESTADO IN ('SOLICITADO', 'PENDIENTE', 'ENTREGADO')) ENABLE,
  CONSTRAINT TC_FACTURA_PK PRIMARY KEY (SFID),
  CONSTRAINT TC_FK_CLIENTE
    FOREIGN KEY (SFCLIENTE)
    REFERENCES TC_PERSONA(SPID),
  CONSTRAINT TC_FK_PROVEEDOR
    FOREIGN KEY (SFPROVEEDOR)
    REFERENCES TC_PROVEEDOR(SPID)
);
CREATE SEQUENCE "DB_SEMILLERO"."SEQ_FACTURA" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;


insert into TC_FACTURA (SFID,SFCLIENTE,SFPROVEEDOR, SFIVA,SFTOTAL,SFTIPO,SFESTADO)
values (DB_SEMILLERO.SEQ_FACTURA.nextval,1,1,22456.37,132096.32,'VENTA','SOLICITADO');

CREATE TABLE TC_FACTURA_DETALLE
( SDID VARCHAR2(50) NOT NULL,
  SDFACTURA_ID NUMBER(10) NOT NULL,
  SDCOMIC_ID NUMBER(10),
  SDCANTIDAD NUMBER(10),
  SDPRECIO_UNITARIO NUMBER(20),
  CONSTRAINT TC_DETALLE_PK PRIMARY KEY (SDID),
  CONSTRAINT TC_FK_FACTURA_DETALLE
    FOREIGN KEY (SDFACTURA_ID)
    REFERENCES TC_FACTURA(SFID),
  CONSTRAINT TC_FK_COMIC
    FOREIGN KEY (SDCOMIC_ID)
    REFERENCES COMIC(SCID)
);

CREATE SEQUENCE "DB_SEMILLERO"."SEQ_DETALLE" MINVALUE 1 START WITH 1  INCREMENT BY 1 NOCACHE;


insert into TC_FACTURA_DETALLE (SDID,SDFACTURA_ID,SDCOMIC_ID, SDCANTIDAD,SDPRECIO_UNITARIO)
values (DB_SEMILLERO.SEQ_DETALLE.nextval,1,7,3‬,36546‬);